dolls:
    - Abigail
    - Aki
    - Angela
    - Antonina
    - Banxsy
    - Betty
    - Bonee
    - Centaureissi
    - Chanzhi
    - Chelsea
    - Choco
    - Croque
    - Dushevnaya
    - Earhart
    - Evelyn
    - Fern
    - Florence
    - Fresnel
    - Gin
    - Groove
    - Hubble
    - Imhotep
    - Jessie
    - Ksenia
    - Lam
    - Mai
    - Max
    - Nanaka
    - Octogen
    - Panakeia
    - Persicaria
    - Rise
    - Sakuya
    - Simo
    - Sol
    - Souchun
    - Vee
    - Yanny
    - Zion
